// Code generated by runway. DO NOT EDIT.

//go:build ignore

package main

import (
	"encoding/json"
	"os"
	"reflect"
	"strings"

	api "{{ .ImportPath }}"
)

type FieldMeta struct {
	Name     string `json:"name"`
	Type     string `json:"type"`
	JSON     string `json:"json,omitempty"`
	Query    string `json:"query,omitempty"`
	Param    string `json:"param,omitempty"`
	Header   string `json:"header,omitempty"`
	Validate string `json:"validate,omitempty"`

	Nested *TypeMeta `json:"nested,omitempty"`
}

type TypeMeta struct {
	Name   string      `json:"name"`
	Fields []FieldMeta `json:"fields,omitempty"`
}

type RouteMeta struct {
	ID          string   `json:"id"`
	Method      string   `json:"method"`
	Path        string   `json:"path"`
	Summary     string   `json:"summary,omitempty"`
	Description string   `json:"description,omitempty"`
	Tags        []string `json:"tags,omitempty"`

	Request  *TypeMeta `json:"request,omitempty"`
	Response *TypeMeta `json:"response,omitempty"`

	StatusCode int `json:"status_code"`
}

func buildTypeMeta(v any) *TypeMeta {
	if v == nil {
		return nil
	}

	t := reflect.TypeOf(v)
	for t.Kind() == reflect.Ptr {
		t = t.Elem()
	}

	if t.Kind() != reflect.Struct {
		return nil
	}

	meta := &TypeMeta{
		Name: t.Name(),
	}

	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		ft := f.Type

		field := FieldMeta{
			Name:     f.Name,
			Type:     ft.String(),
			JSON:     tagValue(f.Tag.Get("json")),
			Query:    f.Tag.Get("query"),
			Param:    f.Tag.Get("param"),
			Header:   f.Tag.Get("header"),
			Validate: f.Tag.Get("validate"),
		}

		// unwrap pointers
		for ft.Kind() == reflect.Ptr {
			ft = ft.Elem()
		}

		// вложенный struct (но не time.Time)
		if ft.Kind() == reflect.Struct && ft.PkgPath() != "time" {
			field.Nested = buildTypeMeta(reflect.New(ft).Elem().Interface())
		}

		if ft.Kind() == reflect.Slice {
			elem := ft.Elem()
			for elem.Kind() == reflect.Ptr {
				elem = elem.Elem()
			}

			if elem.Kind() == reflect.Struct {
				field.Nested = buildTypeMeta(reflect.New(elem).Elem().Interface())
			}
		}

		meta.Fields = append(meta.Fields, field)
	}

	return meta
}

func tagValue(tag string) string {
	if tag == "" {
		return ""
	}
	parts := strings.Split(tag, ",")
	return parts[0]
}

func statusCode(v any) int {
	if v == nil {
		return 204
	}

	val := reflect.ValueOf(v)
	m := val.MethodByName("StatusCode")
	if !m.IsValid() {
		return 200
	}

	out := m.Call(nil)
	if len(out) != 1 {
		return 200
	}

	return int(out[0].Int())
}

func main() {
	var p api.Routes
	routes := p.Routes()

	out := make([]RouteMeta, 0, len(routes))

	for id, r := range routes {
		out = append(out, RouteMeta{
			ID:          string(id),
			Method:      r.Method,
			Path:        r.Path,
			Summary:     r.Summary,
			Description: r.Description,
			Tags:        r.Tags,
			Request:     buildTypeMeta(r.Request),
			Response:    buildTypeMeta(r.Response),
			StatusCode:  statusCode(r.Response),
		})
	}

	_ = json.NewEncoder(os.Stdout).Encode(out)
}
