// Code generated by runway. DO NOT EDIT.

//go:build ignore

package main

import (
	"encoding/json"
	"os"
	"reflect"

	api "{{ .Pkg }}"
)

type RouteMeta struct {
	ID       string `json:"id"`
	Method   string `json:"method"`
	Path     string `json:"path"`
	Request  string `json:"request,omitempty"`
	Response string `json:"response,omitempty"`

	Summary     string   `json:"summary,omitempty"`
	Description string   `json:"description,omitempty"`
	Tags        []string `json:"tags,omitempty"`

	Raw bool `json:"raw"`
}

func typeName(v any) string {
	if v == nil {
		return ""
	}

	t := reflect.TypeOf(v)

	for t.Kind() == reflect.Ptr {
		t = t.Elem()
	}

	if t.PkgPath() != "" {
		return t.Name()
	}

	return t.String()
}

func main() {
	var p api.Routes
	routes := p.Routes() // map[RouteID]runway.Route

	out := make([]RouteMeta, 0, len(routes))

	for id, r := range routes {
		out = append(out, RouteMeta{
			ID:          string(id),
			Method:      r.Method,
			Path:        r.Path,
			Request:     typeName(r.Request),
			Response:    typeName(r.Response),
			Summary:     r.Summary,
			Description: r.Description,
			Tags:        r.Tags,
			Raw:         r.Raw,
		})
	}

	_ = json.NewEncoder(os.Stdout).Encode(out)
}
