// Code generated by runway. DO NOT EDIT.

package {{ .Package }}

import (
    "context"
    "net/http"

    "github.com/labstack/echo/v4"
)

type Router interface {
    {{- range .Routes }}
    {{ .Method }}(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc)
    {{- end }}
}

func RegisterRoutes(r Router, h {{ .Module }}Handlers) {
    a := &{{ .Module }}Adapter{h: h}

    {{- range .Routes }}
    r.{{ .Method }}(
        "{{ .Path }}",
        a.{{ .HandlerName }},
        {{- range .Middlewares }}
        {{ . }},
        {{- end }}
    )
    {{- end }}
}

type {{ .Module }}Handlers interface {
    {{- range .Routes }}
    {{ .HandlerName }}(
        ctx context.Context,
        req {{ .RequestType }},
    ) ({{ .ResponseType }}, error)
    {{- end }}
}

type {{ .Module }}Adapter struct {
    h {{ .Module }}Handlers
}

{{ range .Routes }}
func (a *{{ $.Module }}Adapter) {{ .HandlerName }}(c echo.Context) error {
    var req {{ .RequestType }}

    {{- range .PathParams }}
    req.{{ . | title }} = c.Param("{{ . }}")
    {{- end }}

    if err := c.Bind(&req); err != nil {
        return err
    }

    resp, err := a.h.{{ .HandlerName }}(
        c.Request().Context(),
        req,
    )
    if err != nil {
        return err
    }

    return c.JSON(http.StatusOK, resp)
}
{{ end }}
