// Code generated by runway. DO NOT EDIT.

package {{ .Package }}

import (
    "context"
    "net/http"

    "github.com/labstack/echo/v4"
)

type Router interface {
    {{- range .Routes }}
    {{ .Method }}(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc)
    {{- end }}
}

func RegisterRoutes(r Router, h {{ .Module }}Handlers) {
    a := &{{ .Module }}Adapter{h: h}
    routes := Routes{}.Routes()

    {{- range .Routes }}
    r.{{ .Method }}(
        "{{ .Path }}",
        a.{{ .Id }},
        routes["{{ .Id }}"].Middlewares...,
    )
    {{- end }}
}

type {{ .Module }}Handlers interface {
    {{- range .Routes }}
    {{- if .Request }}
    {{- if .Response }}
    {{ .Id }}(ctx context.Context, req {{ .Request }}) ({{ .Response }}, error)
    {{- else }}
    {{ .Id }}(ctx context.Context, req {{ .Request }}) error
    {{- end }}
    {{- else }}
    {{- if .Response }}
    {{ .Id }}(ctx context.Context) ({{ .Response }}, error)
    {{- else }}
    {{ .Id }}(ctx context.Context) error
    {{- end }}
    {{- end }}
    {{- end }}
}

type {{ .Module }}Adapter struct {
    h {{ .Module }}Handlers
}

{{ range .Routes }}
func (a *{{ $.Module }}Adapter) {{ .Id }}(c echo.Context) error {
    {{- if .Request }}
    var req {{ .Request }}

    if err := c.Bind(&req); err != nil {
        return err
    }
    {{- end }}

    {{- if and .Request .Response }}
    resp, err := a.h.{{ .Id }}(c.Request().Context(), req)
    {{- else if .Request }}
    err := a.h.{{ .Id }}(c.Request().Context(), req)
    {{- else if .Response }}
    resp, err := a.h.{{ .Id }}(c.Request().Context())
    {{- else }}
    err := a.h.{{ .Id }}(c.Request().Context())
    {{- end }}

    if err != nil {
        return err
    }

	{{- if .Response }}
	code := http.StatusOK
	
	if sc, ok := any(resp).(interface{ StatusCode() int }); ok {
	    code = sc.StatusCode()
	}
	
	return c.JSON(code, resp)
	{{- else }}
	return c.NoContent(http.StatusNoContent)
	{{- end }}
}
{{ end }}
