{{- if .Options.ORM.Ent }}
// Code generated by runway, DO NOT EDIT.
package ent

//go:generate go run -mod=mod entgo.io/ent/cmd/ent generate --feature sql/upsert --feature sql/lock --target . ./../schema
{{- end }}